// <auto-generated />
namespace Hess.DataLayer.Migrations.Shop
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class V1001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V1001));
        
        string IMigrationMetadata.Id
        {
            get { return "202211281410107_V1001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
